### PR TITLE
More spells

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sweetriverfish** [comment]
The ap/ad scales are wrong(at least some of them), also gp's E...

**Comment by ghost** [comment]
I used http://leagueoflegends.wikia.com/wiki/League_of_Legends_Wiki as my source, that's why some of the values are "wrong", one could browse the Wiki History and use the values from 4.20 patch, but I'm lazy to do that. Also, getEffectValue() does not work out of the box in some spells.

Sorry about Gangplank's E, I was testing some particles with it, ignore the file if this gets accepted, or edit it later.

**Comment by benank** [comment]
@joaquin95 Use http://ddragon.leagueoflegends.com/tool/ to get all of the values instead of the wiki if you want up to date values.

And apparently you can change the realm to 4.20.  Or at least on mine I can.

**Comment by ghost** [comment]
@noobasaurus Thank you, I can select 4.20 as well. I will change the values in the future.

**Comment by sweetriverfish** [comment]
@joaquin95 also, note that some abilities (ex: cait r) scales only with bonus ad, and you made it to scale with total ad.

**Comment by kaui** [comment]
what version is 4.20? ( release number? 0.0.1.97?)

**Comment by Jaymus3** [comment]
That information could easily be found on the forums with a simple search.

**Pull request closed without merging**
